import { NextRequest } from 'next/server';
import { getAuthUserId } from '@/lib/auth';
import { db } from '@/lib/db';
import { internalErrorResponse, successResponse, unauthorizedResponse } from '@/lib/api-response';

/**
 * GET /api/mage/chats — list the signed-in user's recent Mage conversations for
 * the panel's history overlay. Only threads that actually hold messages are
 * returned (a freshly-created empty "New Chat" is skipped until its first turn,
 * and its title is auto-generated by chat-stream then), newest first.
 */
export async function GET(request: NextRequest) {
  try {
    const userId = await getAuthUserId(request);
    if (!userId) return unauthorizedResponse();

    const chats = await db.notebookChat.findMany({
      where: { userId, messages: { some: {} } },
      orderBy: { updatedAt: 'desc' },
      take: 40,
      select: { id: true, title: true, contextKey: true, updatedAt: true },
    });
    return successResponse({ chats });
  } catch (error) {
    console.error('[mage/chats GET]', error);
    return internalErrorResponse();
  }
}

/**
 * POST /api/mage/chats — start a fresh conversation for the current surface.
 * Creates an empty thread (no messages yet) scoped to (userId, contextKey) and
 * returns its id; the panel points its active chat at it so the next send opens
 * a brand-new thread instead of resuming the surface's latest one. Empty threads
 * are excluded from GET above, so clicking "New chat" and never sending leaves
 * no clutter behind.
 */
export async function POST(request: NextRequest) {
  try {
    const userId = await getAuthUserId(request);
    if (!userId) return unauthorizedResponse();

    const body = (await request.json().catch(() => ({}))) as { contextKey?: string };
    const contextKey = (body.contextKey ?? 'global').slice(0, 200) || 'global';

    const chat = await db.notebookChat.create({
      data: { userId, notebookId: null, contextKey, title: 'New Chat' },
      select: { id: true, contextKey: true },
    });
    return successResponse(chat);
  } catch (error) {
    console.error('[mage/chats POST]', error);
    return internalErrorResponse();
  }
}
