import { NextRequest } from 'next/server';
import { getAuthUserId } from '@/lib/auth';
import { db } from '@/lib/db';
import {
  badRequestResponse,
  internalErrorResponse,
  notFoundResponse,
  successResponse,
  unauthorizedResponse,
} from '@/lib/api-response';

/**
 * GET /api/mage/chats — list the signed-in user's recent Mage conversations for
 * the panel's history overlay. Only threads that actually hold messages are
 * returned (a freshly-created empty "New Chat" is skipped until its first turn,
 * and its title is auto-generated by chat-stream then), newest first.
 */
export async function GET(request: NextRequest) {
  try {
    const userId = await getAuthUserId(request);
    if (!userId) return unauthorizedResponse();

    const chats = await db.notebookChat.findMany({
      where: { userId, messages: { some: {} } },
      orderBy: { updatedAt: 'desc' },
      take: 40,
      select: {
        id: true,
        title: true,
        contextKey: true,
        updatedAt: true,
        allowWebSearch: true,
        allowGeneralKnowledge: true,
      },
    });
    return successResponse({ chats });
  } catch (error) {
    console.error('[mage/chats GET]', error);
    return internalErrorResponse();
  }
}

/**
 * POST /api/mage/chats — start a fresh conversation for the current surface.
 * Creates an empty thread (no messages yet) scoped to (userId, contextKey) and
 * returns its id; the panel points its active chat at it so the next send opens
 * a brand-new thread instead of resuming the surface's latest one. Empty threads
 * are excluded from GET above, so clicking "New chat" and never sending leaves
 * no clutter behind.
 */
export async function POST(request: NextRequest) {
  try {
    const userId = await getAuthUserId(request);
    if (!userId) return unauthorizedResponse();

    const body = (await request.json().catch(() => ({}))) as { contextKey?: string };
    const contextKey = (body.contextKey ?? 'global').slice(0, 200) || 'global';

    const chat = await db.notebookChat.create({
      data: { userId, notebookId: null, contextKey, title: 'New Chat' },
      select: { id: true, contextKey: true, allowWebSearch: true, allowGeneralKnowledge: true },
    });
    return successResponse(chat);
  } catch (error) {
    console.error('[mage/chats POST]', error);
    return internalErrorResponse();
  }
}

/**
 * PATCH /api/mage/chats — set this thread's consent grants (sticky per
 * conversation). Body `{ chatId, allowWebSearch?, allowGeneralKnowledge? }`;
 * only the provided booleans are updated. Ownership is re-authorized by
 * (id, userId), so a forged chatId 404s. Manual validation (no zod), mirroring
 * app/api/user/settings/route.ts. Returns the updated grant values so the
 * client store can never go stale. (Web *execution* is P5 — a web grant here is
 * flag-only.)
 */
export async function PATCH(request: NextRequest) {
  try {
    const userId = await getAuthUserId(request);
    if (!userId) return unauthorizedResponse();

    const body = (await request.json().catch(() => ({}))) as {
      chatId?: unknown;
      allowWebSearch?: unknown;
      allowGeneralKnowledge?: unknown;
    };

    const { chatId } = body;
    if (typeof chatId !== 'string' || chatId.length === 0) {
      return badRequestResponse('chatId must be a non-empty string');
    }

    const data: { allowWebSearch?: boolean; allowGeneralKnowledge?: boolean } = {};
    if (body.allowWebSearch !== undefined) {
      if (typeof body.allowWebSearch !== 'boolean') {
        return badRequestResponse('allowWebSearch must be a boolean');
      }
      data.allowWebSearch = body.allowWebSearch;
    }
    if (body.allowGeneralKnowledge !== undefined) {
      if (typeof body.allowGeneralKnowledge !== 'boolean') {
        return badRequestResponse('allowGeneralKnowledge must be a boolean');
      }
      data.allowGeneralKnowledge = body.allowGeneralKnowledge;
    }
    if (Object.keys(data).length === 0) {
      return badRequestResponse('No grant changes provided');
    }

    const owned = await db.notebookChat.findFirst({
      where: { id: chatId, userId },
      select: { id: true },
    });
    if (!owned) return notFoundResponse('Chat not found');

    const updated = await db.notebookChat.update({
      where: { id: chatId },
      data,
      select: { id: true, allowWebSearch: true, allowGeneralKnowledge: true },
    });
    return successResponse(updated);
  } catch (error) {
    console.error('[mage/chats PATCH]', error);
    return internalErrorResponse();
  }
}
