'use client';

import { useState, useEffect, useRef, useMemo } from 'react';
import { signIn, useSession } from 'next-auth/react';
import { useRouter, useSearchParams } from 'next/navigation';
import OnboardingScreen from './OnboardingScreen';
import AccountStep from './AccountStep';
import UsernameStep from './UsernameStep';
import TierSelectionStep from './TierSelectionStep';
import PaymentStep from './PaymentStep';
import AvatarStep from './AvatarStep';
import StudyGoalsStep, { EMPTY_GOAL_VALUES, type GoalValues } from './StudyGoalsStep';
import ScholarNameStep, { MAGE_NAME_REGEX } from './ScholarNameStep';
import type { TierKey } from '@/lib/tiers';

/**
 * The placeholder username prefix generated by the NextAuth signIn
 * callback for brand-new OAuth users. MUST match OAUTH_USERNAME_PREFIX
 * in src/lib/registration.ts. Duplicated here because client components
 * can't import from server-only modules without extra ceremony, and this
 * is a single string constant unlikely to drift.
 */
const OAUTH_USERNAME_PREFIX = 'oauth_';

type StepId = 'account' | 'plan' | 'avatar' | 'mageName' | 'goals';

/** Ordered flow — drives the progress bar fill. */
const STEP_ORDER: readonly StepId[] = ['account', 'plan', 'avatar', 'mageName', 'goals'];

interface FormData {
  username: string;
  email: string;
  name: string;
  password: string;
  confirmPassword: string;
  agreed: boolean;
  selectedTier: TierKey;
  avatarUrl: string | null;
  scholarName: string;
  goals: GoalValues;
}

/** Suggest a starting username by sanitizing the email prefix. */
function suggestUsernameFromEmail(email: string | null | undefined): string {
  if (!email) return '';
  const base = email.split('@')[0] || '';
  // Strip everything outside the allowed [a-zA-Z0-9_] set, clamp to 20.
  const cleaned = base.replace(/[^a-zA-Z0-9_]/g, '').slice(0, 20);
  return cleaned.toLowerCase();
}

const INITIAL_FORM: FormData = {
  username: '',
  email: '',
  name: '',
  password: '',
  confirmPassword: '',
  agreed: false,
  selectedTier: 'FREE',
  avatarUrl: null,
  scholarName: '',
  goals: { ...EMPTY_GOAL_VALUES },
};

export default function OnboardingWizard() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { data: session, status: sessionStatus, update: updateSession } = useSession();
  const [step, setStep] = useState<StepId>('account');
  const [formData, setFormData] = useState<FormData>(() => {
    const tierParam = searchParams.get('tier')?.toUpperCase();
    const initialTier =
      tierParam === 'PLUS' || tierParam === 'PRO' ? (tierParam as TierKey) : 'FREE';
    return { ...INITIAL_FORM, selectedTier: initialTier };
  });
  const [loading, setLoading] = useState(false);
  const [stepErrors, setStepErrors] = useState<Partial<Record<StepId, string>>>({});
  const [showPayment, setShowPayment] = useState(false);
  const [avatarBusy, setAvatarBusy] = useState(false);
  const paymentHandledRef = useRef(false);

  /**
   * Detect path: OAuth users arrive at /auth/register with an existing
   * session whose username still starts with `oauth_*` (set by the
   * NextAuth signIn callback). Credentials users arrive unauthenticated
   * and create their session in AccountStep.
   */
  const isOauthPath = useMemo(() => {
    const u = session?.user?.username;
    return typeof u === 'string' && u.startsWith(OAUTH_USERNAME_PREFIX);
  }, [session?.user?.username]);

  // For OAuth users, pre-fill avatar from the OAuth profile picture so
  // AvatarStep shows their existing image instead of a blank slate.
  useEffect(() => {
    if (!isOauthPath) return;
    const oauthAvatar = session?.user?.avatarUrl;
    if (oauthAvatar && !formData.avatarUrl) {
      setFormData((prev) => ({ ...prev, avatarUrl: oauthAvatar }));
    }
    // Only ever fire when we first discover we're on the OAuth path —
    // after the user edits the avatar we must not clobber their choice.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOauthPath, session?.user?.avatarUrl]);

  const setStepError = (s: StepId, msg: string) =>
    setStepErrors((prev) => ({ ...prev, [s]: msg }));

  const clearStepError = (s: StepId) => setStepErrors((prev) => ({ ...prev, [s]: '' }));

  // Handle return from Stripe Embedded Checkout (redirect-based flow)
  useEffect(() => {
    const paymentSuccess = searchParams.get('payment_success');
    const sessionId = searchParams.get('session_id');

    if (paymentSuccess !== 'true' || !sessionId || paymentHandledRef.current) {
      return;
    }

    // Mark as handled immediately to prevent re-entry from dependency changes
    paymentHandledRef.current = true;

    // Clear URL params so this effect cannot re-trigger on remount
    const url = new URL(window.location.href);
    url.searchParams.delete('payment_success');
    url.searchParams.delete('session_id');
    window.history.replaceState({}, '', url.pathname + url.search);

    (async () => {
      try {
        const statusRes = await fetch(`/api/stripe/checkout/status?session_id=${sessionId}`);
        const statusData = await statusRes.json();

        if (statusData.data?.status !== 'complete') return;

        // Verify and fulfill tier directly with Stripe (fallback if webhook is delayed)
        await fetch('/api/stripe/checkout/verify', { method: 'POST' });

        await updateSession();
        setStep('avatar');
      } catch {
        paymentHandledRef.current = false;
      }
    })();
  }, [searchParams, updateSession]);

  const handleFieldChange = (field: string, value: string | boolean) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  // ── Step 1 (OAuth path): UsernameStep finished ───────────────────────────
  const handleUsernameSaved = async (username: string) => {
    // Refresh the JWT so session.user.username reflects the real handle
    // (not the oauth_* placeholder). Downstream steps read username from
    // session; without updateSession() AvatarStep would show the placeholder.
    setFormData((prev) => ({ ...prev, username }));
    try {
      await updateSession();
    } catch {
      // Non-fatal — the value is persisted server-side; the next middleware
      // hop will pick it up.
    }
    setStep('plan');
  };

  // ── Step 1 (credentials path): Register + auto-login ─────────────────────
  const handleAccountNext = async () => {
    clearStepError('account');
    setLoading(true);
    try {
      const res = await fetch('/api/auth/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          username: formData.username,
          email: formData.email,
          name: formData.name,
          password: formData.password,
        }),
      });
      const data = await res.json();
      if (!res.ok) {
        setStepError('account', data.error || 'Failed to create account');
        return;
      }
      // Auto-login
      const signInResult = await signIn('credentials', {
        email: formData.email,
        password: formData.password,
        redirect: false,
      });
      if (signInResult?.error) {
        setStepError('account', 'Account created but auto-login failed. Please log in manually.');
        return;
      }
      // Clear sensitive data from state
      setFormData((prev) => ({ ...prev, password: '', confirmPassword: '' }));
      setStep('plan');
    } catch {
      setStepError('account', 'Something went wrong. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  // ── Step 2: Tier Selection ────────────────────────────────────────────────
  const handleTierNext = async () => {
    clearStepError('plan');

    if (formData.selectedTier === 'FREE') {
      // Free tier: save directly and advance
      setLoading(true);
      try {
        const res = await fetch('/api/user/tier', {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ tier: 'FREE' }),
        });
        if (!res.ok) {
          const data = await res.json();
          setStepError('plan', data.error || 'Failed to save plan.');
          return;
        }
        await updateSession();
        setStep('avatar');
      } catch {
        setStepError('plan', 'Something went wrong. Please try again.');
      } finally {
        setLoading(false);
      }
    } else {
      // Paid tier: show embedded Stripe checkout
      setShowPayment(true);
    }
  };

  // ── Payment success handler ──────────────────────────────────────────────
  const handlePaymentSuccess = async () => {
    // Verify and fulfill tier directly with Stripe (fallback if webhook is delayed)
    try {
      await fetch('/api/stripe/checkout/verify', { method: 'POST' });
    } catch {
      // Verification failed — tier may still be updated by webhook later
    }
    await updateSession();
    setShowPayment(false);
    setStep('avatar');
  };

  const handlePaymentBack = () => {
    setShowPayment(false);
  };

  // ── Step 3: Avatar ────────────────────────────────────────────────────────
  const handleAvatarNext = () => {
    setStep('mageName');
  };

  const handleAvatarSkip = () => {
    setFormData((prev) => ({ ...prev, avatarUrl: null }));
    setStep('mageName');
  };

  const handleAvatarChange = (url: string) => {
    setFormData((prev) => ({ ...prev, avatarUrl: url }));
  };

  // ── Step 4: Mage Name ─────────────────────────────────────────────────────
  const handleMageNameNext = () => {
    const trimmed = formData.scholarName.trim();
    if (trimmed && !MAGE_NAME_REGEX.test(trimmed)) {
      setStepError(
        'mageName',
        'Name can only contain letters, numbers, spaces, hyphens, and apostrophes.'
      );
      return;
    }
    clearStepError('mageName');
    setStep('goals');
  };

  const handleMageNameSkip = () => {
    setFormData((prev) => ({ ...prev, scholarName: '' }));
    clearStepError('mageName');
    setStep('goals');
  };

  // ── Step 5: Goals ─────────────────────────────────────────────────────────
  const submitOnboarding = async (goals: GoalValues) => {
    clearStepError('goals');
    setLoading(true);
    try {
      const scholarName = formData.scholarName.trim() || null;
      await fetch('/api/user/onboarding', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ goals, scholarName }),
      });
      // Refresh the JWT token so middleware sees onboardingComplete: true
      await updateSession();
      router.push('/dashboard');
    } catch {
      setStepError('goals', 'Something went wrong. Please try again.');
      setLoading(false);
    }
  };

  const handleGoalsFinish = () => submitOnboarding(formData.goals);
  const handleGoalsSkip = () => submitOnboarding({ ...EMPTY_GOAL_VALUES });

  // Back navigation is only offered on screens that mutate local formData
  // and sit after every irreversible action (account creation, payment).
  const handleBack = () => {
    if (step === 'goals') setStep('mageName');
    else if (step === 'mageName') setStep('avatar');
  };

  const progress = (STEP_ORDER.indexOf(step) + 1) / STEP_ORDER.length;
  const isWide = step === 'plan' && !showPayment;
  const goalCount = Object.values(formData.goals).filter((v) => v !== null).length;

  const goalsBadge =
    goalCount > 0 ? (
      <span
        style={{
          width: '24px',
          height: '24px',
          borderRadius: '9999px',
          background: '#4dff91',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          boxShadow: '0 4px 12px rgba(77,255,145,0.35), 0 0 0 3px var(--surface-container-low)',
        }}
      >
        <span
          className="material-symbols-outlined"
          style={{ fontSize: '15px', color: '#0c2a14', fontVariationSettings: "'FILL' 1, 'wght' 700" }}
        >
          check
        </span>
      </span>
    ) : undefined;

  const renderScreen = () => {
    // ── Step 1: identity — account (credentials) or username (OAuth) ─────────
    if (step === 'account') {
      return (
        <OnboardingScreen screenKey="account" progress={progress}>
          {sessionStatus === 'loading' ? (
            <div
              style={{
                minHeight: '360px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <span
                className="material-symbols-outlined"
                style={{ fontSize: '24px', color: '#ae89ff', animation: 'spin 1s linear infinite' }}
              >
                progress_activity
              </span>
            </div>
          ) : isOauthPath ? (
            <UsernameStep
              suggested={suggestUsernameFromEmail(session?.user?.email)}
              avatarUrl={session?.user?.avatarUrl ?? null}
              displayName={session?.user?.name ?? null}
              onSaved={handleUsernameSaved}
              error={stepErrors.account || ''}
            />
          ) : (
            <AccountStep
              data={{
                username: formData.username,
                email: formData.email,
                name: formData.name,
                password: formData.password,
                confirmPassword: formData.confirmPassword,
                agreed: formData.agreed,
              }}
              onChange={handleFieldChange}
              onNext={handleAccountNext}
              loading={loading}
              error={stepErrors.account || ''}
            />
          )}
        </OnboardingScreen>
      );
    }

    // ── Step 2a: Payment (embedded Stripe sub-screen of Plan) ────────────────
    if (step === 'plan' && showPayment) {
      return (
        <OnboardingScreen screenKey="payment" progress={progress}>
          <PaymentStep
            tier={formData.selectedTier}
            onSuccess={handlePaymentSuccess}
            onBack={handlePaymentBack}
            error={stepErrors.plan || ''}
          />
        </OnboardingScreen>
      );
    }

    // ── Step 2: Plan ─────────────────────────────────────────────────────────
    if (step === 'plan') {
      return (
        <OnboardingScreen
          screenKey="plan"
          progress={progress}
          mascotPose="thinking"
          mascotIdle="sway"
          heading="Choose your plan"
          error={stepErrors.plan || ''}
          primaryLabel={
            loading
              ? 'Saving…'
              : formData.selectedTier === 'FREE'
                ? 'Continue'
                : 'Continue to Payment'
          }
          onPrimary={handleTierNext}
          primaryDisabled={loading}
          primaryLoading={loading}
          compactFooter
        >
          <TierSelectionStep
            selectedTier={formData.selectedTier}
            onSelect={(tier) => setFormData((prev) => ({ ...prev, selectedTier: tier }))}
          />
        </OnboardingScreen>
      );
    }

    // ── Step 3: Avatar ───────────────────────────────────────────────────────
    if (step === 'avatar') {
      return (
        <OnboardingScreen
          screenKey="avatar"
          progress={progress}
          mascotPose="default"
          mascotIdle="bounce"
          heading="Choose your avatar"
          subheading="This is how the community will see you."
          primaryLabel="Continue"
          onPrimary={handleAvatarNext}
          primaryDisabled={loading || avatarBusy}
          secondaryLabel="Skip for now"
          onSecondary={handleAvatarSkip}
          secondaryDisabled={loading || avatarBusy}
        >
          <AvatarStep
            username={formData.username}
            currentAvatarUrl={formData.avatarUrl}
            onAvatarChange={handleAvatarChange}
            onUploadingChange={setAvatarBusy}
          />
        </OnboardingScreen>
      );
    }

    // ── Step 4: Mage Name ────────────────────────────────────────────────────
    if (step === 'mageName') {
      return (
        <OnboardingScreen
          screenKey="mageName"
          progress={progress}
          onBack={handleBack}
          mascotPose="default"
          mascotIdle="bounce"
          heading="Name your Mage"
          subheading="Give your AI study assistant a name."
          error={stepErrors.mageName || ''}
          primaryLabel="Continue"
          onPrimary={handleMageNameNext}
          secondaryLabel="Skip for now"
          onSecondary={handleMageNameSkip}
        >
          <ScholarNameStep
            scholarName={formData.scholarName}
            onChange={(name) => setFormData((prev) => ({ ...prev, scholarName: name }))}
          />
        </OnboardingScreen>
      );
    }

    // ── Step 5: Goals ────────────────────────────────────────────────────────
    return (
      <OnboardingScreen
        screenKey="goals"
        progress={progress}
        onBack={handleBack}
        mascotPose="holding-scroll"
        mascotIdle="sway"
        mascotBadge={goalsBadge}
        heading="Set your goals"
        subheading="Pick what matters to you. You can change these anytime."
        error={stepErrors.goals || ''}
        primaryLabel={
          loading ? (
            'Saving…'
          ) : (
            <>
              Get Started
              <span
                className="material-symbols-outlined"
                style={{ fontSize: '20px', fontVariationSettings: "'FILL' 1" }}
              >
                rocket_launch
              </span>
            </>
          )
        }
        onPrimary={handleGoalsFinish}
        primaryDisabled={loading}
        primaryLoading={loading}
        secondaryLabel="Skip for now"
        onSecondary={handleGoalsSkip}
        secondaryDisabled={loading}
      >
        <StudyGoalsStep
          goals={formData.goals}
          mageName={formData.scholarName.trim()}
          onChange={(goals) => setFormData((prev) => ({ ...prev, goals }))}
        />
      </OnboardingScreen>
    );
  };

  return (
    <div
      style={
        isWide
          ? { width: '90vw', maxWidth: '960px', marginLeft: '50%', transform: 'translateX(-50%)' }
          : undefined
      }
    >
      {renderScreen()}

      {/* Footer links */}
      <div
        style={{
          marginTop: '16px',
          display: 'flex',
          justifyContent: 'center',
          gap: '32px',
        }}
      >
        {['Help Center', 'System Status', 'Contact Support'].map((item) => (
          <a
            key={item}
            href="#"
            className="ob-footer-link"
            style={{
              fontSize: '12px',
              fontWeight: 500,
              color: 'var(--outline)',
              textDecoration: 'none',
            }}
          >
            {item}
          </a>
        ))}
      </div>

      <style>{`
        @keyframes spin {
          from { transform: rotate(0deg); }
          to   { transform: rotate(360deg); }
        }
        .ob-footer-link:hover { color: #e5e3ff; }
        .ob-footer-link:focus-visible { outline: 2px solid #ae89ff; outline-offset: 3px; border-radius: 4px; }
      `}</style>
    </div>
  );
}
