import { NextRequest } from 'next/server';
import { getAuthUserId } from '@/lib/auth';
import {
  successResponse,
  notFoundResponse,
  unauthorizedResponse,
  internalErrorResponse,
} from '@/lib/api-response';
import { checkTokenBudget } from '@/lib/token-budget';
import { mageGenerationActionsEnabled } from '@/lib/feature-flags';
import { loadExamReport } from '@/lib/exam-result';

type Params = { params: Promise<{ id: string }> };

/**
 * Exam Mode (Phase 5) — the post-exam learning report for one exam.
 *
 * The whole report is built from REAL recorded data (grade, target, readiness
 * rollup, weak areas, mock counts, slot progress) with zero AI. The only AI
 * touchpoint is the short report prose, generated by `loadExamReport` only when
 * `useAi` AND nothing is cached on the result yet — then CACHED onto the result,
 * so it fires at most once per exam. PRO gates the AI prose (free tier gets the
 * deterministic narrative); the monthly token budget + the generation
 * kill-switch are honoured. Returns 404 until a result has been recorded.
 */
export async function GET(request: NextRequest, { params }: Params) {
  try {
    const userId = await getAuthUserId(request);
    if (!userId) return unauthorizedResponse();
    const { id: examId } = await params;

    // AI prose only for PRO, with the kill-switch off and token budget intact.
    // Cached after first generation, so a free/over-budget viewer still sees the
    // (deterministic) narrative — just never the AI one.
    let useAi = false;
    if (mageGenerationActionsEnabled()) {
      const { allowed, tier } = await checkTokenBudget(userId);
      useAi = allowed && tier !== 'FREE';
    }

    const report = await loadExamReport(userId, examId, { useAi });
    if (!report) return notFoundResponse('No recorded result for this exam yet.');
    return successResponse(report);
  } catch (error) {
    console.error('[exams/:id/report GET]', error);
    return internalErrorResponse();
  }
}
