'use client';

import { useEffect, useState } from 'react';
import styles from './Docs.module.css';

/* "On this page" rail — links to the doc's h2 headings (ids generated by
   DocsMarkdown), with an IntersectionObserver scroll-spy for the active one. */
export default function DocsToc({ headings }: { headings: { id: string; text: string }[] }) {
  const [active, setActive] = useState(headings[0]?.id ?? '');

  useEffect(() => {
    if (headings.length === 0) return;
    const els = headings
      .map((h) => document.getElementById(h.id))
      .filter((el): el is HTMLElement => el !== null);
    if (els.length === 0) return;

    const io = new IntersectionObserver(
      (entries) => {
        const visible = entries
          .filter((e) => e.isIntersecting)
          .sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top);
        if (visible[0]) setActive((visible[0].target as HTMLElement).id);
      },
      { rootMargin: '-84px 0px -68% 0px', threshold: 0 },
    );
    els.forEach((el) => io.observe(el));
    return () => io.disconnect();
  }, [headings]);

  if (headings.length === 0) return <div />;

  return (
    <aside className={styles.tocRail} aria-label="On this page">
      <div className={styles.tocInner}>
        <div className={styles.tocLabel}>On this page</div>
        <ul className={styles.tocList}>
          {headings.map((h) => (
            <li key={h.id}>
              <a
                href={`#${h.id}`}
                className={`${styles.tocLink} ${active === h.id ? styles.tocLinkActive : ''}`}
              >
                {h.text}
              </a>
            </li>
          ))}
        </ul>
      </div>
    </aside>
  );
}
