import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { assembleTiptap } from './assemble';
import type { DocModelBlock } from './doc-model';
import {
  extractGroundTruth,
  type GroundTruth,
  type GroundTruthPage,
} from './ground-truth';
import { groundTruthToBlocks } from './heuristic-fallback';

// Golden-corpus regression tests. The corpus in `__fixtures__/` is a set of
// committed PDF binaries (generated by scripts/pdf-import-fixtures.ts). These
// tests freeze the DETERMINISTIC stages of import — ground-truth extraction
// and the assembler — so a geometry or assembler regression fails CI. The
// non-deterministic structure-engine stage is covered separately: schema
// validity in engine.test.ts, and human review of the eval harness output.

const readFixture = (name: string): Buffer =>
  readFileSync(fileURLToPath(new URL(`./__fixtures__/${name}`, import.meta.url)));

/** One ground-truth page → its verbatim text (one visual line per row). */
function pageText(page: GroundTruthPage): string {
  return page.lines
    .map((line) => line.cells.map((cell) => cell.text).join(' ').trim())
    .filter((text) => text.length > 0)
    .join('\n');
}

/** A stable digest of a `GroundTruth` — no raw float geometry to snapshot. */
function groundTruthDigest(gt: GroundTruth) {
  return {
    pageCount: gt.pageCount,
    hasTextLayer: gt.hasTextLayer,
    encrypted: gt.encrypted,
    pages: gt.pages.map((page) => ({
      pageNumber: page.pageNumber,
      lineCount: page.lines.length,
      text: pageText(page),
    })),
  };
}

/**
 * The deterministic import pipeline — no LLM. Ground-truth extraction feeds
 * the heuristic fallback (the engine's deterministic stand-in) which feeds
 * the assembler. This is exactly the path import takes when the structure
 * engine is unavailable, and every stage in it is reproducible.
 */
async function deterministicImport(buffer: Buffer) {
  const gt = await extractGroundTruth(buffer);
  const blocks: DocModelBlock[] = [];
  for (const page of gt.pages) blocks.push(...groundTruthToBlocks(page));
  return { gt, ...assembleTiptap({ blocks }) };
}

describe('golden corpus — deterministic pipeline snapshots', () => {
  const fixtures = [
    'clean-text.pdf',
    'multi-column.pdf',
    'callout-heavy.pdf',
    'table-heavy.pdf',
    'image-heavy.pdf',
    'german.pdf',
    // Every-element fixture (~/Downloads/notemage_import_test.pdf): freezes
    // ground-truth extraction over a page that exercises the full block
    // vocabulary. The deterministic path uses the heuristic fallback (no LLM),
    // so the snapshot captures extraction + assembly stability, not the
    // structure engine's richer output.
    'notemage-import-test.pdf',
  ];

  for (const name of fixtures) {
    it(`${name} — extraction and assembly are stable`, async () => {
      const { gt, doc, truncated } = await deterministicImport(readFixture(name));
      expect(gt.encrypted).toBe(false);
      expect(gt.hasTextLayer).toBe(true);
      expect(truncated).toBe(false);
      expect({ groundTruth: groundTruthDigest(gt), doc }).toMatchSnapshot();
    });
  }
});

describe('golden corpus — German non-ASCII', () => {
  it('carries umlauts and the eszett verbatim through the pipeline', async () => {
    const { doc } = await deterministicImport(readFixture('german.pdf'));
    const json = JSON.stringify(doc);
    expect(json).toContain('Überblick');
    expect(json).toContain('Größe');
    expect(json).toContain('grüne');
  });
});

describe('golden corpus — scanned PDF', () => {
  it('has no text layer and falls back to a minimal valid document', async () => {
    const { gt, doc, truncated } = await deterministicImport(readFixture('scanned.pdf'));
    expect(gt.encrypted).toBe(false);
    expect(gt.hasTextLayer).toBe(false);
    expect(gt.pages.every((page) => page.lines.length === 0)).toBe(true);
    expect(truncated).toBe(false);
    // No text layer means the heuristic produces nothing; the assembler's
    // empty-document guard still yields one valid paragraph.
    expect(doc).toEqual({ type: 'doc', content: [{ type: 'paragraph' }] });
  });
});

describe('golden corpus — oversize PDF', () => {
  it('truncates a 200-page PDF and stays under the page-content limit', async () => {
    const { gt, doc, truncated } = await deterministicImport(
      readFixture('giant-200p.pdf'),
    );
    expect(gt.pageCount).toBe(200);
    expect(truncated).toBe(true);
    expect(Buffer.byteLength(JSON.stringify(doc))).toBeLessThan(500_000);
    const last = doc.content[doc.content.length - 1];
    expect(last.type).toBe('callout');
    expect(JSON.stringify(last)).toContain('Import truncated');
  }, 60_000);
});

describe('golden corpus — encrypted PDF', () => {
  it('is detected as encrypted without throwing', async () => {
    const gt = await extractGroundTruth(readFixture('encrypted.pdf'));
    expect(gt.encrypted).toBe(true);
    expect(gt.pageCount).toBe(0);
    expect(gt.pages).toHaveLength(0);
  });
});

describe('golden corpus — corrupt PDF', () => {
  it('rejects rather than producing a broken import', async () => {
    await expect(extractGroundTruth(readFixture('corrupt.pdf'))).rejects.toThrow();
  });
});
